name: specviz

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - jupyter
    - matplotlib
    - numpy
    - scipy
    - docutils
    - Sphinx
    - sphinx_rtd_theme
    - sphinx_automodapi