name: specviz
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - pyyaml
  - cython
  - numpy
  - scipy
  - astropy
  - specutils
  - pyqtgraph
  - sphinx==1.4.8
  - pip:
    - sphinx_automodapi
    - sphinx_rtd_theme
